version: '3.7' 
services: 
  app: 
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'apache2-custom-zapito'
    ports:
      - 8080:80
    volumes:
      - ./shared_web:/var/www/html
  db:
    image: mysql:5.7
    restart: always
    ports: 
      - "3310:3306"
    environment:
      MYSQL_DATABASE: 'zapito_db'
      #MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: "kr@tos_goku"
    volumes:
      - ./shared_db:/var/lib/mysql